#!/bin/sh

URESOURCES=$XDG_CONFIG_HOME/x/Xresources
UBINDKEYS=$XDG_CONFIG_HOME/x/xbindkeysrc
CWMRC=$XDG_CONFIG_HOME/cwm/cwmrc

xbindkeys -f $UBINDKEYS
xrdb -merge $URESOURCES

xsetroot -cursor_name left_ptr
xset -b
xset +fp /usr/share/fonts

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

setxkbmap -layout us,rs -variant ,latin -option grp:caps_toggle
compton -b
fehbg &
lemon &
exec cwm -c $CWMRC
